### ISSUE TITLE
Exception using Vaadin 14.5.1

### ISSUE THREAD

**Issue by SpicyBoyd** [Gubancs/leaflet4vaadin#34]
Hi, we're running the newest Vaadin 14 and are encountering the following exception in **_Production Mode_**.

```
elemental.json.JsonException: 
	at elemental.json.impl.JsonTokenizer.nextString(JsonTokenizer.java:112)
	at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:171)
	at elemental.json.impl.JsonTokenizer.parseObject(JsonTokenizer.java:231)
	at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
	at elemental.json.impl.JsonTokenizer.parseArray(JsonTokenizer.java:192)
	at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:175)
	at elemental.json.impl.JsonTokenizer.parseObject(JsonTokenizer.java:231)
	at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
	at elemental.json.impl.JsonTokenizer.parseArray(JsonTokenizer.java:192)
	at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:175)
	at elemental.json.impl.JsonTokenizer.parseObject(JsonTokenizer.java:231)
	at elemental.json.impl.JsonTokenizer.nextValue(JsonTokenizer.java:173)
	at elemental.json.impl.JreJsonFactory.parse(JreJsonFactory.java:64)
	at elemental.json.Json.parse(Json.java:53)
	at com.vaadin.flow.component.polymertemplate.BundleParser.parseJsonStatistics(BundleParser.java:121)
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.resetCache(NpmTemplateParser.java:249)
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getSourcesFromStats(NpmTemplateParser.java:198)
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:111)
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:221)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.lambda$null$23ee5b4f$1(TemplateInitializer.java:89)
	at com.vaadin.flow.internal.ReflectionCache.lambda$wrapValueProvider$d0062d93$1(ReflectionCache.java:91)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at com.vaadin.flow.internal.ReflectionCache.get(ReflectionCache.java:108)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:90)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:91)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:106)
```

**Desktop (please complete the following information):**
OS: Windows
Browser: Chrome
Version: latest
Vaadin platform version: 14.5.1
Java: 11

**Comment by SpicyBoyd** [comment]
https://github.com/vaadin/flow/issues/10893

fixed version
- Vaadin [14.6.1](https://github.com/vaadin/platform/releases/tag/14.6.1)
- Vaadin Flow ([2.6.1](https://github.com/vaadin/flow/releases/tag/2.6.1))
